### ISSUE TITLE
Div background in footer is on next page.

### ISSUE THREAD

**Issue by headdetect** [mpdf/mpdf#241]
### I have this problem/would like to have this functionality

Trying to change the background in my footer pushes the background element outside of the footer.

I have an alternating header/footer that restarts on each page. In the footer there's a page count that needs to have a background w/padding. Since I can't use a span (because inline-block isn't allowed) I used a div with background. Changing the page number count to a span w/background works, minus the padding. 

The image result im getting looks something like this:
![image](http://i.imgur.com/Fsbn5mc.png)

Also, not a big deal, but still seems like a problem. The first couple of pixels on the left hand side columns are from the footer background.

### These are mPDF and PHP versions I am using

mPDF: `6.1.2`
PHP: `5.5.9`

### This is a PHP code snippet I use

```php

$mpdf = new mPDF('utf-8', 'A4', '', '', '0', '0', '0', '0', '7', '7');

$mpdf->useSubstitutions = true;
$mpdf->simpleTables = true;

$mpdf->setAutoTopMargin = 'stretch';
$mpdf->setAutoBottomMargin = 'stretch';

$mpdf->autoMarginPadding = 0;
$mpdf->WriteHTML($body);

```

### This is a HTML code snippet I use

```html
<body> 

...

<htmlpagefooter name="firstfooter" style="display:none;">
	<div class="footer-container"  style="padding: 50px 0 15px 32px; margin-top: -55px;">
		<div class="row-fluid" >
			<div class="span9 pull-left"  style="margin-top: 95px;">&nbsp;</div>
			<div class="span3 pull-right">
				<div class="page-number">
					{PAGENO}/{nbpg}
				</div>
			</div>
		</div>
	</div>
</htmlpagefooter>

<htmlpagefooter name="otherfooter" style="display:none; ">
	<div class="footer-container"  style="padding: 50px 0 15px 32px; margin-top: -55px; background: #ff00ff">
		<div class="row-fluid">
			<div class="span3 pull-left" style="margin-top: 95px;">
				IMUGR GO HRRRRRRRRR
			</div>
			<div class="span6 pull-left">&nbsp;</div>
			<div class="span3 pull-right">
				<div class="page-number" style="background: green;">
					{PAGENO}/{nbpg}
				</div>
			</div>
		</div>
	</div>
</htmlpagefooter>

...
```

### This is the CSS I'm using as well

```css
@page {
    header: html_otherheader;
    footer: html_otherfooter;
}

@page :first {
    header: html_firstheader;
    footer: html_firstfooter;
}

...

.page-number {
    color: blue;
    text-align: right;
    font-weight: bold;
    font-size: 12pt;
}

.footer-container {
    height: 90px;
    width: 100%;
}

```
